version: '3.5'

services:
  phantom-proxy:
    image: ghcr.io/lunksnee/minecraft-phantom-proxy:latest
    container_name: phantom-proxy
    network_mode: host  # only works with this mode
    environment:
      - SERVER=example.com:19132 # replace example.com with your remote server address
      # - BIND_PORT=0
      # - BIND_IP=0.0.0.0
      # - TIMEOUT=60
      # - IPV6=1
      # - DEBUG=1
      # - REMOVE_PORTS=1
      # - WORKERS=16
